name: Deploy to Production

on:
  push:
    tags:
      -  'v*.*.*'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy via rsync/SSH
        uses: easingthemes/ssh-deploy@v6.0.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SFTP_HOST }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          REMOTE_PORT: ${{ secrets.SFTP_PORT }}
          SOURCE: "./"
          TARGET: "/home/www/public"
          EXCLUDE: "/.git/, /.github/, .env, .env.example, README.md, LICENSE, composer.json, composer.lock, .gitignore, /vendor/, .htaccess, SECURITY.md"
